spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/library_reservation?characterEncoding=utf-8&&useSSL=false
  jpa:
    show-sql: true
  session:
    store-type: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: localhost
#    port: 6379
server:
  port: 8081
opentime: "8:00:00"
